### ISSUE TITLE
"tr" listed in subtitle of Gmail widget

### ISSUE THREAD

**Issue by raphaelcm** [bonusly/gmail-widget#10]
![screen shot 2016-02-22 at 5 15 58 pm](https://cloud.githubusercontent.com/assets/929080/13234736/2acf1584-d988-11e5-8dce-7905a7684c4b.png)

Should be Bonusly, or perhaps http://bonus.ly. Search other popular extensions for some good examples.

**Comment by supersimple** [comment]
I changed that to read "Bonusly" - available since version 1.0.1
