### ISSUE TITLE
duplicate users in dropdown list

### ISSUE THREAD

**Issue by raphaelcm** [bonusly/gmail-widget#3]
<img width="234" alt="screen shot 2016-02-05 at 12 31 39 pm" src="https://cloud.githubusercontent.com/assets/929080/12853900/9bc76ffc-cc04-11e5-8999-fb4177bd2d91.png">

**Comment by supersimple** [comment]
This issue is fixed in the latest build.
you'll need to go to extensions, and reload the gmail widget after you  pull master in order to see the new widget.
